// This JS code is generated by https://freecodez.com

// Your Javascript Code
const button = document.querySelector(".btn");

button.addEventListener("click", createAnimation);

function createAnimation(event) {
  const x = event.clientX - event.target.offsetLeft;
  const y = event.clientY - event.target.offsetTop;

  const span = document.createElement("span");
  span.style.left = x + "px";
  span.style.top = y + "px";

  this.appendChild(span);

  setTimeout(() => {
    span.remove();
  }, 1000);
}
